# file: raspberry.yml
- hosts: raspberrypi
  become: true
  become_method: sudo
  roles:
    - role: application
      vhost_index: index.html
      vhost_root: /var/www/traversy
      vhost_name: traversy.rasp.io
      app_dir: movie-seat-booking
