---
- assert:
    that:
      - vhost_name is defined
      - vhost_root is defined
      - vhost_index is defined
      - app_dir is defined

# NGINX Instalation
- name: NGINX | Updating apt cache
  apt:
    update_cache: yes

- name: NGINX | Installing NGINX
  apt:
    pkg: nginx
    state: latest

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started

# NGINX vHost
- name: Configure NGINX virtual host
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ vhost_name }}.conf
    owner: root
    group: root
  notify:
    - restart nginx

- name: Create document_root directory
  file:
    path: "{{vhost_root}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Copy form-validation application
  copy:
    src: "../../../{{ app_dir }}"
    dest: "{{vhost_root}}/{{ app_dir }}"
    owner: www-data
    group: www-data
    mode: 0644
